services:
  - type: web
    name: chopra-footwear-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://chopra-footwear.vercel.app
      - key: MONGODB_URI
        value: mongodb+srv://vaibhav:vaibhav123@cluster0.mongodb.net/chopra-footwear?retryWrites=true&w=majority
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1

